export { default as Header } from './login-header/login-header'
export { default as ErrorWrap } from './errorWrap/errorWrap'
export { default as Logo } from './logo/logo'
export { default as Footer } from './footer/footer'
export { default as Router } from './router/router'
